/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisclod.view;

import br.com.sisclod.dao.CidadeDAO;
import br.com.sisclod.dao.EstadoDAO;
import br.com.sisclod.model.Cidade;
import br.com.sisclod.model.Estado;
import br.com.sisclod.model.ModeloTabela;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author rootux
 */
public class FrmCadCidade extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadCidade
     */
    int muda = 1;

    public FrmCadCidade() throws SQLException {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        this.popularComboBox();
       // this.popularTabela();

        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCidade = new javax.swing.JTextField();
        jComboBoxUF = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCidade = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cidades");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cidade..:");

        jTextFieldNomeCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeCidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeCidadeKeyTyped(evt);
            }
        });

        jComboBoxUF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("UF.:");

        jButtonSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dih\\Desktop\\icones\\fantatisk\\png\\project\\Save.png")); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTableCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCidade);

        jButtonEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dih\\Desktop\\icones\\fantatisk\\png\\project\\edit.png")); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dih\\Desktop\\icones\\fantatisk\\png\\project\\trash.png")); // NOI18N
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pesquisar..:");

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyTyped(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dih\\Desktop\\icones\\fantatisk\\png\\project\\add1.png")); // NOI18N
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisclod/util/fotos/lupa_318-80384_1.jpg"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dih\\Desktop\\icones\\fantatisk\\png\\project\\Arrow-turn-left.png")); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Cidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButtonNovo)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonSalvar)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonEditar)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonExcluir)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel4)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (muda == 1) {

            String nome = jTextFieldNomeCidade.getText().toUpperCase();
            String sgUF = (String) jComboBoxUF.getSelectedItem();
            sgUF = sgUF.toUpperCase();

            Cidade cidade = new Cidade();
            cidade.setNome(nome);
            cidade.setEstado(sgUF);

            try {
                CidadeDAO dao = new CidadeDAO();
                dao.gravar(cidade);
                this.popularComboBox();
                this.popularTabela();

                jTextFieldNomeCidade.setText("");
                jComboBoxUF.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);

            } catch (SQLException e) {
                System.out.println("Ocorreu um erro" + e.getMessage());
            }

        } else {

            int idCidade = jTableCidade.getSelectedRow();
            int id = ((int) jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 0));
            String noCidade = jTextFieldNomeCidade.getText().toUpperCase();
            String sgUF = (String) jComboBoxUF.getSelectedItem();
            sgUF = sgUF.toUpperCase();

            Cidade cidade = new Cidade();
            try {
                CidadeDAO dao = new CidadeDAO();

                cidade.setNome(noCidade);
                cidade.setEstado(sgUF);

                cidade.setId(id);
                dao.alterar(cidade);

                this.popularTabela();

                muda = 1;

                jButtonEditar.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                jButtonSalvar.setEnabled(true);
                jButtonCancelar.setEnabled(true);
            } catch (SQLException e) {
                System.out.println("Ocorreu um erro" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        int idCidade = jTableCidade.getSelectedRow();
        int id = ((int) jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 0));
        String noCidade = jTextFieldNomeCidade.getText().toUpperCase();
        String sgUF = (String) jComboBoxUF.getSelectedItem();
        sgUF = sgUF.toUpperCase();

        muda = 2;
        jTextFieldNomeCidade.setEditable(true);
        jComboBoxUF.setEnabled(true);
        jButtonSalvar.setEnabled(true);

        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(true);

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCidadeMouseClicked

        try {
            int id = ((int) jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 0));

            String nome = "" + jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 1);
            String sgUF = "" + jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 2);

            this.jTextFieldNomeCidade.setText(nome);
            this.jComboBoxUF.setSelectedItem(sgUF);
            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jComboBoxUF.setEnabled(false);
            muda = 1;
        } catch (Exception e) {
            System.out.println("Ocorreu um erro" + e.getMessage());

        }

    }//GEN-LAST:event_jTableCidadeMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        int idCidade = jTableCidade.getSelectedRow();
        int id = ((int) jTableCidade.getValueAt(jTableCidade.getSelectedRow(), 0));
        String noCidade = jTextFieldNomeCidade.getText().toUpperCase();
        String sgUF = (String) jComboBoxUF.getSelectedItem();
        sgUF = sgUF.toUpperCase();
        try {

            Cidade cidade = new Cidade();
            CidadeDAO dao = new CidadeDAO();

            cidade.setNome(noCidade);
            cidade.setEstado(sgUF);
            cidade.setId(id);

            dao.excluir(cidade);
            JOptionPane.showMessageDialog(null, "Cidade Excluida com sucesso");

            this.popularTabela();

        } catch (SQLException e) {
            System.out.println("Ocorreu um erro" + e.getMessage());
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jTextFieldNomeCidade.setEditable(false);
        dispose();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        jTextFieldNomeCidade.setEditable(true);
        jComboBoxUF.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        muda = 1;
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
            popularTabela2();
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadCidade.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jComboBoxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUFActionPerformed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonPesquisarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyTyped
        String min = "qwertyuiopasdfghjklçzxcvbnm";

        if (min.contains(evt.getKeyChar() + "")) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
        int limite = 50;
        if (jTextFieldPesquisar.getText().length() >= limite) {
            evt.consume();
        }     }//GEN-LAST:event_jTextFieldPesquisarKeyTyped

    private void jTextFieldNomeCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeCidadeKeyTyped
        String min = "qwertyuiopasdfghjklçzxcvbnm";

        if (min.contains(evt.getKeyChar() + "")) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
        int limite = 50;
        if (jTextFieldNomeCidade.getText().length() >= limite) {
            evt.consume();
        }     }//GEN-LAST:event_jTextFieldNomeCidadeKeyTyped

    private void jTextFieldNomeCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeCidadeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonSalvarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextFieldNomeCidadeKeyPressed

    private void popularComboBox() {

        EstadoDAO dao = null;
        try {
            dao = new EstadoDAO();
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        List<Estado> estados = null;
        try {
            estados = dao.lista();
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBoxUF.removeAllItems();
        for (int i = 0; i < estados.size(); i++) {
            jComboBoxUF.addItem(estados.get(i).getSigla());
        }

    }

    private void popularTabela() throws SQLException {

        jTextFieldNomeCidade.setEditable(false);
        jComboBoxUF.setEditable(false);
        String[] coluna = new String[]{"ID", "NOME", "UF"};
        ArrayList dados = new ArrayList();
        CidadeDAO dao = new CidadeDAO();
        ArrayList<Cidade> listagem;

        listagem = (ArrayList<Cidade>) dao.getLista1();
        for (Cidade cidade : listagem) {
            dados.add(new Object[]{cidade.getId(), cidade.getNome(), cidade.getEstadoTabela()});
        }

        ModeloTabela modelo = new ModeloTabela(dados, coluna);

        try {
            jTableCidade.setModel(modelo);
            jTableCidade.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableCidade.getColumnModel().getColumn(0).setResizable(false);
            jTableCidade.getColumnModel().getColumn(1).setPreferredWidth(600);
            jTableCidade.getColumnModel().getColumn(1).setResizable(false);
            jTableCidade.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCidade.getColumnModel().getColumn(2).setResizable(false);

            jTableCidade.getTableHeader().setReorderingAllowed(false);
            jTableCidade.setAutoResizeMode(jTableCidade.AUTO_RESIZE_OFF);
            jTableCidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar os dados\ndetalhes: " + ex, "Aviso!", 1);
        }

    }

    private void popularTabela2() throws SQLException {

        jTextFieldNomeCidade.setEditable(false);
        jComboBoxUF.setEditable(false);
        String[] coluna = new String[]{"ID", "NOME", "UF"};
        ArrayList dados = new ArrayList();
        CidadeDAO dao = new CidadeDAO();
        ArrayList<Cidade> listagem;

        String pesquisa = jTextFieldPesquisar.getText().toUpperCase();

        listagem = (ArrayList<Cidade>) dao.AcharCidadelista2(pesquisa);
        for (Cidade cidade : listagem) {
            dados.add(new Object[]{cidade.getId(), cidade.getNome(), cidade.getEstado()});
        }

        ModeloTabela modelo = new ModeloTabela(dados, coluna);

        try {
            jTableCidade.setModel(modelo);
            jTableCidade.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableCidade.getColumnModel().getColumn(0).setResizable(false);
            jTableCidade.getColumnModel().getColumn(1).setPreferredWidth(600);
            jTableCidade.getColumnModel().getColumn(1).setResizable(false);
            jTableCidade.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableCidade.getColumnModel().getColumn(2).setResizable(false);

            jTableCidade.getTableHeader().setReorderingAllowed(false);
            jTableCidade.setAutoResizeMode(jTableCidade.AUTO_RESIZE_OFF);
            jTableCidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel listar os dados\ndetalhes: " + ex, "Aviso!", 1);
        }

    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCadCidade().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCadCidade.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCidade;
    private javax.swing.JTextField jTextFieldNomeCidade;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

}
